### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by tomitrescak** [schmuli/atom-karma-runner#1]
Hi, i started to write karma reporter for atom and then I found your project, which looks very promising. Yet, it is not registere as plugin for atom yet and I'm missing info on how to use it. Do you maybe need some help with it?

**Comment by schmuli** [comment]
The plugin is not yet ready for publishing, since I haven't yet completed the UI. Since this is a side-project and I only work on it in my spare time, it is progressing rather slowly.

**Comment by DianaSuvorova** [comment]
Since I stumbled upon this plugin first and realized it is not a workable version. Wanted to  provide a link to karma runner plugin I ended up developing myself: https://atom.io/packages/atom-karma-test-runner. It works! Please try it out!

**Comment by schmuli** [comment]
@DianaSuvorova That is excellent, congratulations!

Unfortunately, I have stopped using Atom as my daily editor, which is why I never got around to finishing this plugin. I also had very grand ideas for the UI, basically I wanted to copy the WebStorm Karma runner UI, which is why it was taking so long to begin with.
